export const ACTION_PROJECT_LAYERS_SET = 'ACTION_PROJECT_LAYERS_SET'
export const ACTION_PROJECT_LAYER_ADD = 'ACTION_PROJECT_LAYER_ADD'
export const ACTION_PROJECT_LAYER_DELETE = 'ACTION_PROJECT_LAYER_DELETE'
export const ACTION_PROJECT_LAYER_MOVE = 'ACTION_PROJECT_LAYER_MOVE'

export const ACTION_USER_SETTINGS_LAYER_MAKE_CURRENT = 'ACTION_USER_SETTINGS_LAYER_MAKE_CURRENT'
export const ACTION_USER_SETTINGS_SET_LAYER_VISIBLE = 'ACTION_USER_SETTINGS_SET_LAYER_VISIBLE'
export const ACTION_USER_SETTINGS_SET_LAYER_CLUSTER = 'ACTION_USER_SETTINGS_SET_LAYER_CLUSTER'
